### ISSUE TITLE
how to switch to dark mode？

### ISSUE THREAD

**Issue by francismiko** [themefisher/bigspring-light-astro#1]
i tried to alter tailwindcss.config.js & Base.astro, but it seems does't work.

**Comment by tfsomrat** [comment]
Hello @Francismiko 
We don't have dark mode functionality for this theme. If you really want to add dark mode on your own, you need to set up a tailwind configuration and add `dark:*` classes to every component.

Or you can contact us for custom service here: https://themefisher.com/contact (PAID)
