### ISSUE TITLE
Mailbox Setting

### ISSUE THREAD

**Issue by Eventidus** [themefisher/bigspring-light-astro#3]
Hello, what should I do to be able to send emails normally?
![image](https://github.com/themefisher/bigspring-light-astro/assets/49816387/6f41bdbd-8854-4405-86c5-441570e35e99)

**Comment by tfsomrat** [comment]
Use Third-party service like formsubmit.co, formspree.io etc

**Comment by Eventidus** [comment]
Thank you! But I don't know why when I configure the contact_form_action property in the config.json file, I sent a test email but my destination email didn't receive the mail, and also when I send it the webpage directly jumps to the homepage. I don't know if I sent it successfully, by the way, I'm using formsubmit.co.

**Comment by tfsomrat** [comment]
your `contact_form_action` will look like this `https://formsubmit.co/your@mail.com`. then submit a form will send you an email to active the form.

**Comment by Eventidus** [comment]
Surprisingly, it really works! Thank you so much!!!
